language: php

branches:
  # Only test the master branch and semantic version tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

sudo: false

env:
  global:
    - TERMINUS_TEST_MODE=1
    - COMPOSER_PROCESS_TIMEOUT=3600

before_script:
  - set -ex
  - composer install --no-interaction --prefer-dist

script:
  - composer clover
  - phpenv config-rm xdebug.ini # XDebug is needed for code coverage, but makes things slow. It's enabled by default in Travis, we disable it here post-coverage run for speedy builds.
  - composer cs
  - composer phpunit
  - composer behat

after_success:
    - if [ $(phpenv version-name) = "7.0" ]; then composer coveralls; fi

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache
