# TERMINUS CONSTANTS
#
# These are default values for each of the constants bearing the same name
# within Terminus. They may be overridden by exporting an environmental
# variable of the same name, or by adding it to a file named ".env" in the
# directory from which you are running Terminus.
---

# App
TERMINUS_VERSION: '3.0.0-alpha'

# Connectivity
TERMINUS_HOST:        'terminus.pantheon.io'
TERMINUS_HOST_CERT:   null
TERMINUS_PORT:        443
TERMINUS_PROTOCOL:    'https'
TERMINUS_SSH_HOST:    null
TERMINUS_SSH_COMMAND: 'ssh'

# Settings
TERMINUS_TIMEOUT: 86400
TERMINUS_PLUGINS_FALLBACK_COMPATIBILITY: '2.6.1'

# User Prompts
TERMINUS_DASHBOARD_HOST:     'dashboard.pantheon.io'
TERMINUS_DASHBOARD_PROTOCOL: 'https'

# Localization
TERMINUS_DATE_FORMAT:     'Y-m-d H:i:s'
TERMINUS_MONETARY_FORMAT: '$%01.2f'
TERMINUS_TIME_ZONE:       'UTC'

# File Storage
TERMINUS_CACHE_DIR:             '[[ TERMINUS_USER_HOME ]]/.terminus/cache'
TERMINUS_PLUGINS_DIR:           '[[ TERMINUS_USER_HOME ]]/.terminus/plugins-3.x'
TERMINUS_DEPENDENCIES_BASE_DIR: '[[ TERMINUS_USER_HOME ]]/.terminus/terminus-dependencies'
TERMINUS_COMMAND_CACHE_DIR:     '[[ TERMINUS_CACHE_DIR ]]/commands'
TERMINUS_TOKENS_DIR:            '[[ TERMINUS_CACHE_DIR ]]/tokens'
TERMINUS_ASSETS_DIR:            '[[ TERMINUS_ROOT ]]/assets'
TERMINUS_LOCAL_COPIES:          '[[ TERMINUS_USER_HOME ]]/pantheon-local-copies'
TERMINUS_PHAR_FILE:             '[[ TERMINUS_USER_HOME ]]/terminus'
TERMINUS_EXECUTABLE:            '[[ TERMINUS_USER_HOME ]]/bin/terminus'

# Helpers
TERMINUS_USER: null
TERMINUS_SITE: null
TERMINUS_ENV:  null
TERMINUS_ORG:  null

# Region
TERMINUS_COMMAND_SITE_OPTIONS_REGION: null

# Package Settings
TERMINUS_BREW_TAP:               '*** TBD ***'
TERMINUS_BREW_PACKAGE:           '*** TBD ***'
TERMINUS_DEBIAN_PACKAGE_INSTALL: '*** TBD ***'

# Testing
TERMINUS_TEST_MODE:    false
TERMINUS_VCR_CASSETTE: null
TERMINUS_VCR_MODE:     null

# Set by Terminus - DO NOT USE
# Terminus
# TERMINUS_PHP
# TERMINUS_ROOT
# TERMINUS_SCRIPT

# Debug Guzzle Calls here:
TERMINUS_CLIENT_OPTIONS:
  debug: false
  http_errors: false

