# TERMINUS CONSTANTS
#
# These are default values for each of the constants bearing the same name
# within Terminus. They may be overridden by exporting an environmental
# variable of the same name, or by adding it to a file named ".env" in the
# directory from which you are running Terminus.
---

# App
TERMINUS_VERSION:      '0.12.0'

# Connectivity
TERMINUS_HOST:         'dashboard.pantheon.io'
TERMINUS_PORT:         443
TERMINUS_PROTOCOL:     'https'
TERMINUS_SSH_HOST:     null

# Localization
TERMINUS_DATE_FORMAT:  'Y-m-d H:i:s'
TERMINUS_TIME_ZONE:    'UTC'

# File Storage
TERMINUS_CACHE_DIR:    '~/.terminus/cache'
TERMINUS_CONFIG_DIR:   '~/terminus'
TERMINUS_LOG_DIR:      '/tmp'
TERMINUS_PLUGINS_DIR:  '[[ TERMINUS_CONFIG_DIR ]]/plugins'
TERMINUS_TOKENS_DIR:   '[[ TERMINUS_CACHE_DIR ]]/tokens'
TERMINUS_ASSETS_DIR:   '[[ TERMINUS_ROOT ]]/app/assets'

# Helpers
TERMINUS_USER:         null
TERMINUS_SITE:         null
TERMINUS_ENV:          null
TERMINUS_ORG:          null

# Testing
TERMINUS_TEST_MODE:    false
TERMINUS_VCR_CASSETTE: null
TERMINUS_VCR_MODE:     null

# Set by Terminus - DO NOT USE
# Terminus
# TERMINUS_PHP
# TERMINUS_ROOT
# TERMINUS_SCRIPT
